version: '3.6'

services:
  api:
    build: .
    depends_on:
      - db
    env_file: .env
    environment:
      STAGE: test
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}"
    networks:
      - default
    ports:
      - 5001:5001
    volumes:
      - ./app:/usr/src/app/app
      - ./migrations:/usr/src/app/migrations
    restart: always

  db:
    container_name: postgres
    image: postgres:latest
    env_file: .env
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data